name: Publish to Modrinth
on: [ workflow_dispatch, push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@v4
      - name: Zip Folder
        run: |
          cd Illegalmc
          zip -0 -r IllegalMCT.zip .
      - name: Publishing to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: 'illegal-mct'
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"
          name: "releasenameoption" #${{env.RELEASE_NAME}}
          version: "versionoption" #${{env.VERSION}}
          files: "Illegalmc/IllegalMCT.zip"
          loaders: "vanilla"
